module.exports = {

    Cookies : 'div > span.js-cookie-policy-main-accept-button.cookie-policy-button.is--primary',
    FirstName: '#input_6',
    LastName : '#input_7',
    Pesel : '#input_8',
    Phone : '#input_10',
    Mail1 : '#input_9',
    Mail2 : '#input_306',
    Submit : '#input_next_2',
    Idnumber : '#input_27',
    Day: '#input_303_day > option:nth-child(30)',
    Month: '#input_303_month > option:nth-child(6)',
    Year:'#input_303_year > option:nth-child(6)',
    eDay: '#input_28_day > option:nth-child(30)',
    eMonth:'#input_28_month > option:nth-child(6)',
    eYear: '#input_28_year > option:nth-child(3)',
    BirthPlace: '#input_26',
    MaidenName: '#input_25',
    Street : '#input_31',
    Number : '#input_32',
    PostCode : '#input_34',
    Town : '#input_35',
    No1 : '#graphic_input_46_1',
    No2 : '#graphic_input_42_1',
    karty: 'div.logo-group > div.submenu > div.navi_panel > ul > li.node.lv_0.item_6 > a',
    Cookies : 'div > span.js-cookie-policy-main-accept-button.cookie-policy-button.is--primary',
    more: '#teaser_tiles_2_10102017 > div.content_area > div > div > div.tile_content > div.buttons.textCenter > span',
    visa : '#teaser_tiles_4_13102017 > div.content_area > div > div > div.tile_content > div.buttons.textCenter > span',
    openacc:'#intro_banner_1_02112017 > div.intro_banner_inner > div.content.content_area > p:nth-child(4) > a.button.primary',
    Error : '#error-message-input_8'
};